variables:
  IMAGE_NAME: gcr.io/diamond-pubreg/pato/backend:$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA

image: python:3.11
stages:
  - test

install-job:
  stage: test
  tags:
    - argus
  script:
    - pip install .[dev]

lint-and-integration-test-job:
  stage: test
  tags:
    - argus
  before_script:
    - pip install .[dev]
  script:
    - tox
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cov.xml
